# Generated by Django 3.0.3 on 2020-03-05 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0004_auto_20200304_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(default='{"direction": {"types": ["back", "front", "left", "right"]}, "sex": {"types": ["male", "female"]}, "body": {"types": ["human"], "colors": [["white", "black", "olive", "brown", "peach", "light", "dark", "dark2", "tanned", "tanned2"]], "sprites": "body/{sex}/{color}.png"}, "hair": {"types": ["plain", "bedhead", "loose"], "types_sex": ["male", "male", "female"], "colors": [["blonde", "blue", "brunette", "green", "pink", "raven", "dark_blonde", "white_blonde"], ["blonde", "blue", "brunette", "green", "pink", "raven", "redhead", "white_blonde"], ["black", "blonde", "blonde2", "blue", "blue2", "brown", "brunette", "brunette2", "dark-blonde", "gray", "green", "green2", "light-blonde", "light-blonde2", "pink", "pink2", "raven", "raven2", "redhead", "ruby-red", "white", "white-blonde", "white-blonde2", "white-cyan"]], "sprites": "hair/{sex}/{type}/{color}.png"}, "hats": {"types": [], "sprites": []}, "eyes": {"types": [], "sprites": []}, "facial": {"types": [], "sprites": []}, "nose": {"types": [], "sprites": []}, "ears": {"types": [], "sprites": []}, "jacket": {"types": [], "sprites": []}, "clothes": {"types": [], "sprites": []}, "legs": {"types": [], "sprites": []}, "shoes": {"types": [], "sprites": []}, "boots": {"types": [], "sprites": []}, "weapon": {"types": [], "sprites": []}, "ammo": {"types": [], "sprites": []}}')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='adventure.Player')),
            ],
        ),
    ]
